platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Google Maps
  pod 'GoogleMaps', '~> 8.4'

  # Kotlin Multiplatform Framework
  pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
